// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendFeed(arg1, arg2) {
  return window['go']['main']['App']['AppendFeed'](arg1, arg2);
}

export function DeleteFeed(arg1) {
  return window['go']['main']['App']['DeleteFeed'](arg1);
}

export function GetFeeds() {
  return window['go']['main']['App']['GetFeeds']();
}
