// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendFeed(arg1:string,arg2:string):Promise<string>;

export function DeleteFeed(arg1:string):Promise<Error>;

export function GetFeeds():Promise<string>;
